import Head from 'next/head'
import { useContext, useEffect } from 'react'
import { useRouter } from 'next/router'
import { GlobalContext } from '../_app'
import AccountCart from '@/components/AccountCart'


function Cart() {

    const globalContext = useContext(GlobalContext);

    const router = useRouter();

    useEffect(() => {


        if (globalContext?.initialUserApiCallDone) {

            if (!globalContext?.curentUserInfo?.userName && !globalContext?.curentUserInfo?.userName) { router.push("/"); globalContext.updateLoginRegisterModalIsOpen(true) }

        }

        // eslint-disable-next-line
    }, [globalContext?.curentUserInfo?.userName, router, globalContext?.initialUserApiCallDone]);

    return (
        <>
            <Head>
                <title>My Cart</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {globalContext?.curentUserInfo?.userName ? <AccountCart /> : null}

        </>
    );
}

export default Cart;