import Head from 'next/head'
import { useContext } from "react"
import { GlobalContext } from "../_app";
import AccountOrders from "@/components/AccountOrders";

function Orders() {

    const globalContext = useContext(GlobalContext);

    return (
        <>
            <Head>
                <title>My Orders</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {globalContext?.curentUserInfo?.userName ? <AccountOrders /> : null}
        </>
    );
}

export default Orders;